### ISSUE TITLE
Clarify licensing

### ISSUE THREAD

**Issue by xsawyerx** [xsawyerx/module-starter#1]
Issue #6[1] on google code repo is to clarify the licensing of Module::Starter. The attached patch to the original issue by Shlomi Fish adds to the copyright the "GPL version 1 or at your option a later version" and "Artistic Original, 2.0 or at your option a later version."

I personally prefer to put it on GPLv2.0+ or Artistic 2.0+, since GPLv1 is basically a buggy version of GPLv2, nothing more. There's no reason to keep it GPLv1.

This will be done soon, unless anyone opposes.

[1] http://code.google.com/p/module-starter/issues/detail?id=6

**Comment by ppisar** [comment]
Still broken in 1.71.
