### ISSUE TITLE
support for mercurial [rt.cpan.org #82935]

### ISSUE THREAD

**Issue by xsawyerx** [xsawyerx/module-starter#33]
https://rt.cpan.org/Ticket/Display.html?id=82935

    Attached is a patch against 1.60 which adds support for mercurial
    .hgignore files.  I've modeled it on the .git support (if bald-faced
    duplication can count as modeling).
    
    Thanks,
    
    Diab

**Comment by xsawyerx** [comment]
DJERIUS - 2013-01-24 18:52:09

Ooops.  Forgot to update the docs in module-starter.  Revised patch
attached.

**Comment by chrestomanci** [comment]
I think this bug can be closed. It looks like commit 34433bf8 in GitHub applies Diab's patch

**Comment by xsawyerx** [comment]
Right again! :)
