### ISSUE TITLE
libmodule-starter-perl: Incomplete default MANIFEST: t/boilerplate.t missing [rt.cpan.org #86558]

### ISSUE THREAD

**Issue by xsawyerx** [xsawyerx/module-starter#38]
https://rt.cpan.org/Ticket/Display.html?id=86558

    Hi
    
    This bug has been forwarded from http://bugs.debian.org/711513 reported
    by Axel Beckert.
    
    ----cut---------cut---------cut---------cut---------cut---------cut-----
    Package: libmodule-starter-perl
    Version: 1.600+dfsg-2
    Severity: normal
    
    When creating a new Module::Build based module, module-starter creates
    t/boilerplate.t, but doesn't add it to the MANIFEST:
    
    $ module-starter --module=Foo::Bar --mb --ignore=git --verbose --license=perl --force
    Created Foo-Bar
    Created Foo-Bar/lib/Foo
    Created Foo-Bar/lib/Foo/Bar.pm
    Created Foo-Bar/t
    Created Foo-Bar/t/pod-coverage.t
    Created Foo-Bar/t/pod.t
    Created Foo-Bar/t/manifest.t
    Created Foo-Bar/t/boilerplate.t
    Created Foo-Bar/t/00-load.t
    Created Foo-Bar/.gitignore
    Created Foo-Bar/Build.PL
    Created Foo-Bar/Changes
    Created Foo-Bar/README
    Added to MANIFEST: Build.PL
    Added to MANIFEST: Changes
    Added to MANIFEST: lib/Foo/Bar.pm
    Added to MANIFEST: MANIFEST
    Added to MANIFEST: README
    Added to MANIFEST: t/00-load.t
    Added to MANIFEST: t/boilerplate.t
    Added to MANIFEST: t/manifest.t
    Added to MANIFEST: t/pod-coverage.t
    Added to MANIFEST: t/pod.t
    Created Foo-Bar/MANIFEST
    Created starter directories and files
    $ cd Foo-Bar
    $ perl Build.PL
    Created MYMETA.yml and MYMETA.json
    Creating new 'Build' script for 'Foo-Bar' version '0.01'
    $ ./Build distclean
    Cleaning up build files
    Cleaning up configuration files
    Not in MANIFEST: t/boilerplate.t
    MANIFEST appears to be out of sync with the distribution
    $ 
    
    -- System Information:
    Debian Release: jessie/sid
      APT prefers unstable
      APT policy: (990, 'unstable'), (900, 'testing'), (899, 'testing-proposed-updates'), (600, 'stable'), (500, 'proposed-updates'), (200, 'experimental')
    Architecture: i386 (i686)
    
    Kernel: Linux 3.10-rc4-686-pae (SMP w/2 CPU cores)
    Locale: LANG=en_GB.UTF-8, LC_CTYPE=en_GB.UTF-8 (charmap=UTF-8)
    Shell: /bin/sh linked to /bin/dash
    
    Versions of packages libmodule-starter-perl depends on:
    ii  libpath-class-perl  0.32-1
    ii  perl                5.14.2-21
    
    libmodule-starter-perl recommends no packages.
    
    libmodule-starter-perl suggests no packages.
    
    -- no debconf information
    
    ----cut---------cut---------cut---------cut---------cut---------cut-----
    
    Thanks in advance,
    Salvatore Bonaccorso, Debian Perl Group

**Comment by chrestomanci** [comment]
Is this bug still present ?

I think it was fixed by pull request #45 (now released)

**Comment by xsawyerx** [comment]
Closing. If it happens again, we could reopen.
