### ISSUE TITLE
FSF address is outdated in Module::Starter::Simple and tests [rt.cpan.org #88795]

### ISSUE THREAD

**Issue by xsawyerx** [xsawyerx/module-starter#39]
https://rt.cpan.org/Ticket/Display.html?id=88795

    Hi,
    
    The FSF mailing address changed about 2 years ago.  I created GitHub pull request that updtes the FSF's mailing address in template blocks and tests that use it.
    
    https://github.com/xsawyerx/module-starter/pull/15
    
    Thanks,
    
    Brian

**Comment by chrestomanci** [comment]
I think you can close this one as pull request #15 has been merged.

**Comment by xsawyerx** [comment]
Right you are!
