### ISSUE TITLE
Inconsistent version string format

### ISSUE THREAD

**Issue by satoshi** [xsawyerx/module-starter#53]
When I use the 3-digit version format for $VERSION (0.0.1, for example), the resulting tarball looks like Foo-Bar-0.0.1.tar.gz.  However, the META.json contains "version" : "v0.0.1".  This subtle difference causes an issue where MetaCPAN indexes the distribution based on the tarball filename, while FPM uses the META.json information to determine the version, and the end result is FPM cannot construct a proper URL to fetch and build the module.

If you could somehow make it consistent, that would be great.  I am using ExtUtil::MakeMaker as builder and perl-Module-Starter-1.71-1.fc22.noarch on Fedora 22.

**Comment by karenetheridge** [comment]
I would recommend "0.001" as the default form, but failing that, it should be "0.0.1" not "v0.0.1".

**Comment by satoshi** [comment]
Right.  I am using "v0.0.1" in $VERSION as a workaround to make it consistent, but ideally I wouldn't have to do that and use "0.0.1" which then shows up as "0.0.1" in META.json instead of "v0.0.1".

**Comment by Grinnz** [comment]
This is more of an issue for ExtUtils::MakeMaker as that is the module which is generating your META.json and tarball name.

**Comment by Grinnz** [comment]
Closing as I don't see anything that can be fixed in Module::Starter for this.
